language: php
dist: focal
php:
  - 7.4
  - 8.0
  - 8.1
  - nightly
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
cache:
  directories:
    - vendor
env:
  - ADDENDUM_CACHE_CLEAR=0
  - ADDENDUM_CACHE_CLEAR=1
install:
  # Remove possible obsolete tests
  - bash -c 'if [ -e "vendor/maslosoft/addendumtest" ]; then rm -rf "vendor/maslosoft/addendumtest"; fi;'
  # Required for older php
  - composer update
  - composer install --prefer-dist --dev --no-interaction
  - cd $TRAVIS_BUILD_DIR
script:
  - bash run-travis