language: php
php:
  - 5.6
  - 5.5
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
install:
  - composer install
  - composer update maslosoft/mangantest
before_script:
  - phpenv config-add travis.ini
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.clover
script: vendor/codeception/codeception/codecept --colors --coverage-xml=coverage.clover --coverage-html=. run
#script: phpunit --coverage-clover=coverage.clover --bootstrap vendor/maslosoft/mangantest/bootstrap.php vendor/maslosoft/mangantest/tests