language: php
php:
  - 5.6
  - 5.5
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
install:
  - composer install --dev --prefer-source
  - composer update maslosoft/addendumtest
before_script:
  - phpenv config-add travis.ini
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php php ocular.phar code-coverage:upload --repository=g/Maslosoft/Addendum --revision=`git rev-parse HEAD` --format=php-clover ./tests/_output/coverage.clover
script: vendor/bin/codecept run unit --coverage --html --coverage-html=. --coverage-xml=./coverage.clover
