language: php
dist: trusty
php:
  - 7.1
  - 7.2
  - 7.3
  - nightly
  - hhvm
sudo: false
matrix:
  allow_failures:
    - php:
      - nightly
cache:
  directories:
    - vendor
env:
  - ADDENDUM_CACHE_CLEAR=0
  - ADDENDUM_CACHE_CLEAR=1
install:
  # Remove possible obsolete tests
  - bash -c 'if [ -e "vendor/maslosoft/addendumtest" ]; then rm -rf "vendor/maslosoft/addendumtest"; fi;'
  # Required for php 5
  - composer update
  - composer install --prefer-dist --dev --no-interaction
  - cd $TRAVIS_BUILD_DIR
script:
  - bash run-travis