language: php
dist: trusty
php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm
sudo: false
matrix:
  allow_failures:
    - php:
      - nightly
cache:
  directories:
    - vendor
env:
  - ADDENDUM_CACHE_CLEAR=0
  - ADDENDUM_CACHE_CLEAR=1
install:
  - composer install --dev --prefer-dist
  # Get fresh tests
  - rm -rf vendor/maslosoft/addendumtest
  - git clone https://github.com/Maslosoft/AddendumTest.git vendor/maslosoft/addendumtest
  - cd $TRAVIS_BUILD_DIR
script:
  - bash run-travis