language: php
dist: trusty
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm
sudo: false
matrix:
  allow_failures:
    - php:
      - nightly
cache:
  directories:
    - vendor
env:
  - ADDENDUM_CACHE_CLEAR=0
  - ADDENDUM_CACHE_CLEAR=1
install:
  # Required for php 5
  - composer update
  - composer install --dev --prefer-dist
  - cd $TRAVIS_BUILD_DIR
script:
  - bash run-travis