language: php
php:
  - 5.6
  - 5.5
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php:
      - nightly
env:
  - ADDENDUM_CACHE_CLEAR=0
  - ADDENDUM_CACHE_CLEAR=1
install:
  - composer install --dev --prefer-dist
  - composer update maslosoft/addendumtest
script:
  - run-travis