#!/bin/bash
if [ "$TRAVIS_PHP_VERSION" == "hhvm" ] || [ "$TRAVIS_PHP_VERSION" == "nightly" ]; then
	vendor/bin/codecept run unit
fi;
if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then 
	vendor/bin/codecept run unit --coverage --html --coverage-html=. --coverage-xml=./coverage.clover
fi;
wget --no-check-certificate https://scrutinizer-ci.com/ocular.phar
if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then
	php ocular.phar code-coverage:upload --revision=`git rev-parse HEAD` --format=php-clover ./tests/_output/coverage.clover
fi;
rm ocular.phar