#!/bin/bash
rm -rf runtime/*

version=`php -v`

coverage=false
if [[ $version =~ .*Xdebug.* ]];
then
	coverage=true
fi
if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then
	coverage=false
fi;

if $coverage; then
	echo "Have coverage";
	vendor/bin/codecept run unit --coverage --html --coverage-html=. --coverage-xml=./coverage.clover
	status=$?
	wget --no-check-certificate https://scrutinizer-ci.com/ocular.phar
	php ocular.phar code-coverage:upload --revision=`git rev-parse HEAD` --format=php-clover ./tests/_output/coverage.clover
	rm ocular.phar
else
	echo "No code coverage available"
	vendor/bin/codecept run unit
	status=$?
fi
exit $status